### ISSUE TITLE
Errors when importing a project into Eclipse 2023-03 that uses this plugin

### ISSUE THREAD

**Issue by ctubbsii** [mathieucarbou/license-maven-plugin#523]
**Version affected**

Tried using 4.1, 4.2.rc2, 4.2.rc3

**Describe the bug**

<details>
<summary>
When I import the project into Eclipse 2023-03, I get the following errors (click to expand):
</summary>

```
Description	Resource	Path	Location	Type
Failed to execute mojo com.mycila:license-maven-plugin:4.1:format {execution: license-headers} (com.mycila:license-maven-plugin:4.1:format:license-headers:process-test-resources)

org.eclipse.core.runtime.CoreException: Failed to execute mojo com.mycila:license-maven-plugin:4.1:format {execution: license-headers}
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeMojo(MavenExecutionContext.java:340)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.lambda$0(MavenExecutionContext.java:291)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:290)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:57)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.lambda$1(MavenBuilderImpl.java:139)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:122)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:164)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$1(MavenBuilder.java:109)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:228)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:100)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:214)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:83)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:192)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1020)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:247)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:392)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:395)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:506)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:454)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:536)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:196)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:289)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution license-headers of goal com.mycila:license-maven-plugin:4.1:format failed: Cannot read header document /home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt. Cause: Resource /home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt not found in file system, classpath or URL: no protocol: /home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:148)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeMojo(MavenExecutionContext.java:338)
	... 32 more
Caused by: java.lang.IllegalArgumentException: Cannot read header document /home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt. Cause: Resource /home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt not found in file system, classpath or URL: no protocol: /home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt
	at com.mycila.maven.plugin.license.header.HeaderSource.of(HeaderSource.java:237)
	at com.mycila.maven.plugin.license.AbstractLicenseMojo.executeForLicenseSet(AbstractLicenseMojo.java:459)
	at com.mycila.maven.plugin.license.AbstractLicenseMojo.executeForLicenseSets(AbstractLicenseMojo.java:429)
	at com.mycila.maven.plugin.license.AbstractLicenseMojo.execute(AbstractLicenseMojo.java:391)
	at com.mycila.maven.plugin.license.LicenseFormatMojo.execute(LicenseFormatMojo.java:69)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	... 33 more
Caused by: org.apache.maven.plugin.MojoFailureException: Resource /home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt not found in file system, classpath or URL: no protocol: /home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt
	at com.mycila.maven.plugin.license.util.resource.ResourceFinder.findResource(ResourceFinder.java:112)
	at com.mycila.maven.plugin.license.header.HeaderSource.of(HeaderSource.java:233)
	... 38 more
Caused by: java.net.MalformedURLException: no protocol: /home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt
	at java.base/java.net.URL.<init>(URL.java:674)
	at java.base/java.net.URL.<init>(URL.java:569)
	at java.base/java.net.URL.<init>(URL.java:516)
	at com.mycila.maven.plugin.license.util.resource.ResourceFinder.findResource(ResourceFinder.java:107)
	... 39 more
	pom.xml	/accumulo-core	line 24	Maven Build Problem
```

</details>

**How to Reproduce**

1. Download Eclipse for Java Developers package
2. Import the Apache Accumulo project (https://github.com/apache/accumulo) at commit `e79532a2d69429e8fdce3f75c1c3121f5673b856` using `Import projects -> Maven -> Existing Maven Projects -> Select root directory of checkout -> Click Finish`
3. See the errors

Notably, I didn't get an error in the top-level module of the multi-module project. Only in the child modules. The error seems to show that it can't read the license-header.txt file, but it exists and works fine when running the plugin from Maven command-line.

**Additional details**

This worked without issue in previous versions of Eclipse. It worked fine in 2022-09, and after upgrading to 2022-12. It also seemed to work after upgrading to 2023-03, but it did not work on a fresh install.

When I tried to import another (smaller, single module) project (https://github.com/revelc/formatter-maven-plugin), it seemed to have trouble resolving the Eclipse plugin from the M2E marketplace.

I'm reporting it here as a starting place. I don't know if the issue is with this plugin, the M2E marketplace, or Eclipse itself.

**Comment by hazendaz** [comment]
Gut tells me m2e.  I'm on 2022 12 and most parts of 2023 03.  No issues until I updated m2e again last night.  Then same issue tonight.  IMHO m2e is a complete mess.  Look at their issue tickets.  It's sky rocketed.  Want until you close and re open poms only to get complete failure and have to restart eclipse.  It's been a major, major issue since they moved to modern language servers and release constantly and in some cases go backwards on released version numbers.  Even code navigation is entirely broken in the poms.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Christopher Tubbs ***@***.***>
Sent: Thursday, March 23, 2023 10:57:40 PM
To: mathieucarbou/license-maven-plugin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mathieucarbou/license-maven-plugin] Errors when importing a project into Eclipse 2023-03 that uses this plugin (Issue #523)


Version affected

Tried using 4.1, 4.2.rc2, 4.2.rc3

Describe the bug

When I import the project into Eclipse 2023-03, I get the following errors (click to expand):

Description     Resource        Path    Location        Type
Failed to execute mojo com.mycila:license-maven-plugin:4.1:format {execution: license-headers} (com.mycila:license-maven-plugin:4.1:format:license-headers:process-test-resources)

org.eclipse.core.runtime.CoreException: Failed to execute mojo com.mycila:license-maven-plugin:4.1:format {execution: license-headers}
        at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeMojo(MavenExecutionContext.java:340)
        at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.lambda$0(MavenExecutionContext.java:291)
        at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
        at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
        at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:290)
        at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:57)
        at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.lambda$1(MavenBuilderImpl.java:139)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:122)
        at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:164)
        at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
        at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$1(MavenBuilder.java:109)
        at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
        at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:228)
        at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:100)
        at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:394)
        at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
        at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:214)
        at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:83)
        at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:192)
        at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1020)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:247)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
        at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:392)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:395)
        at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:506)
        at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:454)
        at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:536)
        at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:196)
        at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:289)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution license-headers of goal com.mycila:license-maven-plugin:4.1:format failed: Cannot read header document /home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt. Cause: Resource /home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt not found in file system, classpath or URL: no protocol: /home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:148)
        at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeMojo(MavenExecutionContext.java:338)
        ... 32 more
Caused by: java.lang.IllegalArgumentException: Cannot read header document /home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt. Cause: Resource /home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt not found in file system, classpath or URL: no protocol: /home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt
        at com.mycila.maven.plugin.license.header.HeaderSource.of(HeaderSource.java:237)
        at com.mycila.maven.plugin.license.AbstractLicenseMojo.executeForLicenseSet(AbstractLicenseMojo.java:459)
        at com.mycila.maven.plugin.license.AbstractLicenseMojo.executeForLicenseSets(AbstractLicenseMojo.java:429)
        at com.mycila.maven.plugin.license.AbstractLicenseMojo.execute(AbstractLicenseMojo.java:391)
        at com.mycila.maven.plugin.license.LicenseFormatMojo.execute(LicenseFormatMojo.java:69)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        ... 33 more
Caused by: org.apache.maven.plugin.MojoFailureException: Resource /home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt not found in file system, classpath or URL: no protocol: /home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt
        at com.mycila.maven.plugin.license.util.resource.ResourceFinder.findResource(ResourceFinder.java:112)
        at com.mycila.maven.plugin.license.header.HeaderSource.of(HeaderSource.java:233)
        ... 38 more
Caused by: java.net.MalformedURLException: no protocol: /home/christopher/git/apache/accumulo/accumulo/core/contrib/license-header.txt
        at java.base/java.net.URL.<init>(URL.java:674)
        at java.base/java.net.URL.<init>(URL.java:569)
        at java.base/java.net.URL.<init>(URL.java:516)
        at com.mycila.maven.plugin.license.util.resource.ResourceFinder.findResource(ResourceFinder.java:107)
        ... 39 more
        pom.xml /accumulo-core  line 24 Maven Build Problem


How to Reproduce

  1.  Download Eclipse for Java Developers package
  2.  Import the Apache Accumulo project (https://github.com/apache/accumulo<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fapache%2Faccumulo&data=05%7C01%7C%7C36d5b931026e41fe56e408db2c138882%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638152234631636776%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Z8dOrr7QGnjMzrbaWGw%2FpRjc5lYdqkRuZVcIMQLZ4UQ%3D&reserved=0>) at commit e79532a2d69429e8fdce3f75c1c3121f5673b856 using Import projects -> Maven -> Existing Maven Projects -> Select root directory of checkout -> Click Finish
  3.  See the errors

Notably, I didn't get an error in the top-level module of the multi-module project. Only in the child modules. The error seems to show that it can't read the license-header.txt file, but it exists and works fine when running the plugin from Maven command-line.

Additional details

This worked without issue in previous versions of Eclipse. It worked fine in 2022-09, and after upgrading to 2022-12. It also seemed to work after upgrading to 2023-03, but it did not work on a fresh install.

When I tried to import another (smaller, single module) project (https://github.com/revelc/formatter-maven-plugin<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frevelc%2Fformatter-maven-plugin&data=05%7C01%7C%7C36d5b931026e41fe56e408db2c138882%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638152234631636776%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2Bksc3mpvxg1eyURSZI0Y%2F1WTpYszXDDlu8172b5UhtU%3D&reserved=0>), it seemed to have trouble resolving the Eclipse plugin from the M2E marketplace.

I'm reporting it here as a starting place. I don't know if the issue is with this plugin, the M2E marketplace, or Eclipse itself.

**Comment by ctubbsii** [comment]
> Gut tells me m2e.

I think you might be right. I couldn't even get the build-helper plugin to work right until I installed the complete M2E Development kit, which comes with all M2E plugins.

**Comment by ctubbsii** [comment]
Confirmed it works fine with Eclipse 2022-09, but the 2022-12 has the same issues being unable to resolve the Eclipse plugin that affects 2023-03. It also works fine after upgrading back to 2023-03. One thing I noticed was that the resolved 	`basepom.org	m2e extension for the Mycila license plugin.	1.1.0	org.basepom.m2e.mycila-license` plugin was not signed. Maybe that has something to do with it.

**Comment by mathieucarbou** [comment]
@ctubbsii  will close. The plugin code uses standard Maven Plugin annotations for teh dev. It has and cannot have any effect on IDE support...

**Comment by ctubbsii** [comment]
Oh, since the MalformedURLException in the stack trace appeared to be coming from this plugin, I thought perhaps the bug was coming from this plugin somehow.

**Comment by hazendaz** [comment]
I thought I added m2e stuff here from 4.2 but may have missed.  With m2e now they auto magically figure things out rather than warn users.  Connectors are a bit different.  It's worth looking more into.

Also I run snapshot p2 from m2e due to excessive issues.  They didn't get m2e 2.x in eclipse until 2022 12 and it was buggy then.  It's better but issues persist.  I was fine too here until I opened project yesterday after latest m2e snapshot and I did get errors on the git and svn modules only.  I wasn't overly concerned knowing m2e broken today usually has some other fix within days.

M2e suggestions have been to use the snapshots due to all of this.  I don't fault them here.  M2e hardly ever changed and they are trying to modernize but results are extremely mixed to say the least.  It also doesn't help eclipse is doing same and breaking a lot along the way.  Groovy was completely broken without hacking osgi settings for a while too.

Main thing is this is the cost of fail fast and letting users test it.  Unfortunately for those of us that love eclipse this is making intellij more appealing.  At the end though I think they are trying to really get this on par with all other ide's but eclipses fragmented plugin environment makes that 100 times more difficult.

And I love eclipse.  I don't want to use intellij bit at a corporate level it's really hard to justify.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
